# -*- Mode: org ; Coding: utf-8-unix -*-
#+SETUPFILE: ../0000/00org-web-template
#+TITLE: 日本代表が理解できる人と理解できない人の決定的な違い
#+DESCRIPTION:
#+KEYWORDS: football japan worldcup 2018
#+SUBTITLE:
#+OPTIONS: ^:{}

今回のW杯カップ、日本代表の試合は面白かったですね。 選手たちは一生懸命でした。 果敢に挑む姿が印象的でした。 ベスト8の夢をみました。 大会前から色々ありましたけど、いい試合がみられたと思います。

テーマはサポーターです。

タモさんがNHKスペシャル「戦後70年」の特集で、こんなことを対談していました。

タモリ「江戸から明治にかけても同じことが起きていたんだよね。 明治になったら、江戸のもの全部否定した。 仏像や絵画も。 あんな世界的な価値を認められた浮世絵も包装紙にして。 簡単に日本は前のもの捨て去るんですね」

堺雅人「リセットしてゼロから始めたがる傾向が我々にはあるのかな。 でも生き残っている人の歴史だから終戦から続いていると思う。 リセットできない脈々と続いている何か、文化、心意気とか。 何かが続いている。 リセット、簡単にしちゃいけない」

スケールは違いますが、あなたの身近にもいませんか。 うまくいかないと、全部丸めてゴミ箱にポイと投げ、白紙の紙を取り出す人。 新しい社長になったら仕事のやり方がすべて変わったという経験。

大会直前、代表監督が解任されました。 この時、日本代表はリセットされたのでしょうか。 私にはリセットされることを拒否したようにもみえました。 すなわち、ハリルを中心とした「なにか」がうまくいっておらず「全部捨てた」という見方がひとつ。 一方で、脈々と続いている「なにか」を「捨てたくなかった」という見方もできました。

解任劇は大きな話題を呼び、どちらも継続というキーワードで語られました。 ハリルを継続するのか、日本のサッカーを継続するのか。 日本のサッカーとは何なのか。前回大会との関連は何か。結局、ザックジャパンの中心的なメンバーが「最後までやらせてくれ」と訴え、それを受け入れることになりました。 その後、若干の修正を加えて到達できたのが、ベルギー戦です。

試合後、選手たちは「最高のチームだった」「全員一丸となって戦えた」「このチームでもう少し試合をしたかった」と述べています。 このような発言はよい結果が出たチームや優勝したチームでよく聞かれる言葉です。 今回の代表が成功した証しだと思います。実に清々しい。

しかしながら、今回の流れを継続することは困難です。 ベテラン選手が代表を引退し、中心となった柴崎選手も、次の大会では30歳を超えてしまうからです。 長谷部選手の引退表明が、苦しくもこれを暗示しています。 「この大会を最後に日本代表へひとつの区切りをつけたい」

継続を選択したのに継続できないとは、 なんという皮肉でしょうか。 ハリルの言葉が胸に刺さります。

ハリル「日本には多くの才能あふれる若者がいます。 W杯という大舞台で活躍できるだけのものを持っている若者がいるのです。 西野監督はベテランを中心に23人を選びました。 代表チームというのは社会福祉事業ではないというのに」

思い起こせば、カズの時代、中田の時代、本田の時代と、それぞれに区切りがありました。 時代と時代の関係性は薄く、同じことを繰り返しているように思えます。 なぜ、こんなことが起きてしまうのでしょうか。

代表という言葉には、2つの側面があります。 1つは「最高のアスリートを選び出だす」という意味。 もう1つは「僕たちの代表」という意味です。 世界最高峰の祭典で最高のプレイヤーに競わせる「代表」と、私やあなたの代わりに意思を世界へ発信する「代表」があります。しかしながら、前者の意味だけが日本には浸透しているようです。 三浦和良に憧れ、中田英寿に陶酔し、本田圭佑にプロフェッショナルを感じている人が日本ではサポーターだと呼ばれています。 ピッチに立っている選手が自分の代わりだと思う人はほとんどいません。

海外リーグで活躍する選手から共通して伝えられる言葉があります。 「こっちのサポーターは本当に熱い。 しかも、よくサッカーを知っている。 良いプレーをしたら拍手が、悪いプレーをしたらブーイングが飛んでくる」と。

「世界中のサッカーが観られる唯一の国」それが日本だとオシムが言いました。あれからどれだけの月日が流れたでしょうか。なぜ日本人は、いまなおサッカーを知らないのでしょうか。 世界のオッサンは、なぜサッカーをよく知っているのでしょうか。 あらゆる情報や戦術を手にできる日本人が、なぜ世界から取り残されているのでしょうか。 自分の好きなチームだけを応援する世界のオッサンは、なぜ最先端のサッカーを理解できるのでしょうか。

ロンドンの郊外にザ・バレーと呼ばれる場所があります。 1919年、土地の権利をサッカークラブが購入しましたが、スタジアムを作るお金がなかったようです。 そこでボランティアでサポーターが集り、スコップで土を掘り、ピッチを作りました。余った土砂をピッチ脇に積み上げてスタンドをつくりました。 突如、山と谷(バレー)ができたところから、その名がついています。 当時のイングランドでは最大規模のスタジアムであり、7万人以上を収容できました。 しかし、1984年、財政破綻。 スタジアムを売り払うことになりました。 ですが、再びボランティアが立ちあがります。 政党「ザ・バレー」を立ちあげ、選挙に打って出るのです。 議席を取り、議会で提案し、スタジアムを取り返します。 2018年の現在でもイングランドらしい美しいスタジアムがそこにはあります。

そろそろ日本サポーターも気づくべきです。 あなたの好きな選手は、長くても12年程度しかいないのです。 その選手がどんなに上手くても、どんなに魅力的でも、プレーできる時間はごく僅かです。 しかし、あなたが日本代表のサポーターである時間は永遠です。 あなたの手に抱かれている子供も、そして、またその子供も日本代表のサポーターなのです。有名監督や天才選手が日本代表を牽引するのではありません。 この先、あなたが日本代表をつくっていくのです。

海外のオッサンが世紀をまたいで共有しているものは人生の哲学です。 みんながビールマニアでありえても戦術マニアであるはずがありません。彼らは自分達の価値観をピッチにぶつけているのです。 彼らにとって選手はアイドルではありません。 自分たちの鏡です。 生まれ育った土地の文化を表現してくれるのが選手なのです。 自分の考えと違うプレーをしたらブーイングを、自分と同じであれば拍手をしているのが世界のオッサンの秘密なのです。

今の日本代表に足りないものはサポーターの意識です。 選手は誰だっていいのです。 自分の心意気を射影するためにピッチがあります。 日本代表に文化を投影させる必要があります。海外でヘディング 1 つに拍手が、スライディング 1 つにブーイングが起きるのは、自分自身がそこにいるからです。 何かやりたいことがある選手をサポートするのはサポーターではありません。「今日の試合はお前に頼んだ。俺はサポートにまわるから、あとはしっかりやってくれ」というのがサポーターなのです。そして、試合の中から自分自身の価値観を引きだすのがサッカー観戦なのです。

多くの日本人選手が世界へ出て行きました。 彼らは世界から賞賛されるプレーをみせてくれるようになりました。 次はサポーターの番です。 世界標準へ一気にかけ上がりましょう。 日本代表はサポーターの進化を待っています。

え? 何をすればいいか分からない? 簡単です。 週末、近くのスタジアムに行き、いいなと思ったプレーに拍手を、嫌だなって思ったプレーにブーイングをすればよいのです。 高度な戦術を知っている必要はありません。 恥ずかしがる必要もありません。 あなたの思いをピッチの選手に伝えればいいだけです。 それが本当のサッカー文化です。

あなたの声援が日本代表そのものを作っていく、そんな日本代表が生まれればいいな、と思います。


おまけ

Dennis Bergkamp の言葉を紹介します。 

When you start supporting a football club, you don't support it because of the trophies, or a player, or history, you support it because you found yourself somewhere there; found a place where you belong.


*このおとぎ話が通じたのは残念ながら 15 年前までです。 今はもう時代が変わってしまいました。 それを象徴するのがメッシの登場と今大会の彼の敗退です。 したがって、この先のベスト 8 は違う文脈で語られるべきです。 
