# -*- Mode: org ; Coding: utf-8 -*-
#+SETUPFILE: ../0000/00org-web-template
#+TITLE: グループリーグ突破から見えてきた日本のサッカー
#+DESCRIPTION:
#+KEYWORDS: football japan worldcup 2018
#+SUBTITLE:
#+OPTIONS: ^:{}

「つまらない」「金返せ」「スポーツ精神に反する」という意見、分かります。こういう事が起こらないように、サッカーもルールを変えてきましたが、十分ではありません。未熟なスポーツだと思います。

「勝負に徹する」「どんな手を使っても勝つ」という意見、分かります。僕たちはドーハの悲劇を見てきました。最後の最後に手から溢れ落ちる。もうそんなのはごめんです。勝っていても負けていても、次のステージに進めるのであれば、試合を放棄しましょう。なんの否定もしません。

それでも、セネガルに奇跡が起こらないという博打だけは理解できませんでした。僕は、毎週、毎週、好きな J リーグのチームを応援しています。諦めず戦い抜けと、奇跡を起こせと、応援しています。きっとサッカーを好きなみんながそうしているはずです。そして、あなたもその目で奇跡を何度も見てきたはずです。そうじゃないと、サッカーを好きなはずがない。

セネガルは素晴らしいチームでした。日本を最大限にリスペクトしてくれました。日本と戦ったあと、セネガルの監督はこう言ってくれました。

「悔しさもあります。ですが、世界の皆さんに今日のようなゲームをお届けできて、嬉しく思います。サッカーは南米やヨーロッパだけのものではありません。アジアやアフリカでも遜色ないゲームができる。今日はこれが分かっていただけたと思うし、これを誇りに思っています」

サッカーはロスタイムに一番点の入るスポーツです。もし、セネガルが追いついたら...。その時、日本がボール遊びをしていたら...。そう思うと目も当てられませんでした。奇跡や悲劇といったレベルではありません。単なるアホの坂田になってしまいます。

誠実にサッカーと向き合い、相手を尊重し、献身的にプレーをする。それがサッカーだと教わってきました。相手に運命を任せることは、サッカーへの冒涜に思えました。あの日、日本は何も手にしていなかった。そして何も手に入れようとしなかった。

1日たって、ようやく理解できました。開幕直前、監督が変わり、本当の日本が生まれるという意味を。

何かを欲するわけでもなく、何かに怯えるわけでもない。あるがままを受け入れ、なりゆきを見守る。これが新たな日本のサッカー。これが本当のサムライブルー。色即是空。空即是色。負けられない南無阿弥陀仏。

なるほど。意味が分からない。

ガンバレ、仏陀ジャパン。

今日もサッカーをみたいと思います。
