#+SETUPFILE: ../0000/00org-web-template
#+TITLE: 2015 年版、買って良かったもの
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:

去年の 10 月から脱ニートを行い、社畜 1 年生。会社で利用するものや出張用のものなどを少し購入した。社会人 1 年目なので、リンクはアフィリエイトです。

- SATO マルチタイマー TM-30 http://amzn.to/1Xe3leR
  
  タスク管理に家では[[http://amzn.to/1lINMuJ][パール金属 バイブレーション タイマー レッド C-3240]] を使用していて問題なかったけど、社内で使うと周りの人からウルサイとの文句があったので、変更した。これは光だけでアラームしてくれる機能のみ使っている。これで他の人の邪魔にはならない。と、この記事を書いている時に、同僚からもっと良さそうな [[http://amzn.to/1NpYFYw][OHM デュオタイマー COK-TD1 809955]] を紹介してもらったため、こちらを買おうか悩み中。
  
- オズマ プラグ付き充電器 ILAU50-01K http://amzn.to/1lIPeNW

  コンセントのプラグ付き充電器。サッカー遠征、出張用で新幹線社内でバッテリーだけを充電しておいたり、ホテルでケーブルが届かない時に、バッテリーだけ充電しておくことで、その後が快適になる。

- スピルリナ http://amzn.to/1lISZD1

  下痢と便秘に悩まされていたが、これを飲むと便秘はなくなった(下痢はある)。はじめて飲んだ時は体の調子も良くびっくりした(最近は慣れてしまった)。

- Twiter クライアント Absolutter https://goo.gl/XPwmzK

  ツイ廃用クライアントで、びよーんったーの後継版。[[http://togetter.com/li/827062][Twitter 初夏の Ban まつり]]で、びよーんったーが規制を受けたことと、携帯を [[http://amzn.to/1lIS7hE][FREETEL SAMURAI MIYABI (ブラック)]] へ機種変したことにより、こちらを購入。びよーんったーより洗練されているかな。

- サンワサプライ PC スタンド CR-LAST3 http://amzn.to/1Xe9SWX

  スタンディングデスクでの作業って、ここ数年ずっとバズられてるけど、PC ケースで良いサイズのもの([[http://amzn.to/1OhiUwI][SilverStone Precision SST-PS08B]])がやっとみつかったので、こちらも購入。

- LOGICOOL ワイヤレストラックボールマウス M570t http://amzn.to/1Xe9lo3

  [[http://amzn.to/1Xe9SWX][サンワサプライ PC スタンド CR-LAST3]] のマウススペースは非常に狭いため購入。(右利きだけど)マウスは左手で使う派だから、左手用のものがあれば仕事でも使えるのだけども。

- ECOVER ゼロ ファブリックコンディショナー http://amzn.to/1ThhVMV
  
  香りのある柔軟剤は気管支や喘息に非常に悪いため、使わない方がいいが、これだと大丈夫そうだと思い購入。今のところ問題なし。

- SHOP JAPAN トゥルースリーパーネオフィール http://amzn.to/1IJJYnN

  ベッドマットのスプリングが壊れてしまって、半年後に買い替える予定だから、その繋ぎとしてのベッドパット。たしかに寝ているときの沈み具合はいいかんじ。
  
