* 2019-04-15
** 18:54

   時刻が入らない問題は

   [[https://gitmemory.com/mrvdb][mrvdb ( Marcel van der Boom )]] の以下が起きていることが分かった。
   
   #+begin_example
   Messages buffer has: user-error: There was no year zero ( I missed this the first time)
   Tried again from scratch, but first issuing org-reload before org-journal-new-entry which made it work.
   #+end_example

   特に、以下を設定すると怪しいことも分かった。
   
   #+begin_src elisp
   (setq org-journal-dir "~/Dropbox/journal")
   #+end_src

   でも、プログラミングが分からないから、これ以上は分からない。
   調べたくない。
   つらい。

   夕方 16:30 ぐらいに疲れて寝てしまった。
   つらい。
   明日から新しい職場だというのに大丈夫だろうか。
   不安だ。

   午前中はメルカリで売れたキーボードを送るために、ダンボールを無料でくれるところはないかと歩き回ったりした。
   最近はどこもくれない。
   売っているものだから、というのが理由らしい。
   よく分からない。
   最後の頼みだったスーパーの超冷たいおばちゃんがくれた。
   優しいんだかなんだか。
   持ってきたダンボールは超ピッタリサイズで嬉しくなった。
   写真撮って相方に送ろうかと思うほどだった。
   やめたけど。

   英語の履歴書というか職務経歴書も書いた。
   簡単なもの。
   明日からの職場が合わなければ、すぐに出せるようにというところで。
   不安だ。

   xmodmap は古いというのをみて、変えようと少し調べた。
   xmodmap の書き方も不明だし。
   xkb や xkeysnail というのがあると分かった。
   費用対効果を考えて、変えるのはやめた。
   動いてるし。
   ubuntu では動かないらしい。
   明日からの職場の PC ではキーマップを変えられるだろうか。
   不安だ。

   Trello で蔵書管理するというアイディアを実践しようとした。
   かなりいいアイディアだと思うのだが、リスト名を何にして、いくつつくるかという仕様のところで挫折した。
   PDF と Kindle と現物もあるし。
   ラベルというのを利用したら、ラベルの色名が org-trello でタグとしてインポートされる仕様だと分かった。
   そりゃないだろう。
   pdf というlabel をつけたところ :sky: とか出てきたし(色が sky だった)。
   プログラミングが分からないから、これ以上は調べない。
   つらい。

   そういえば、今日が前職?の正式な退職日だ。
   保険証を返却するために郵便局に行った。
   封筒付きのものをくれると思ったのだが、それは現金書留だけだということだった。
   カード型の超小さい封筒に入れていったので、普通の封筒を買うハメになった。
   つらい。

   郵便局に置いてある糊を使って封をしようとしたら、スポンジみたいになっている塗るところが取れて、中の糊がドバッと出てきて作業台に広がった。
   ティシュをもらい、拭いたりした。
   つらい。

   朝、メルカリ用のプチプチを購入するために、ドンキへ行ったのだが、そこで無脂肪牛乳を買うのを忘れた。
   Trello で買い物管理しようというところなのに、忘れた。
   また夕方行ったりした。
   つらい。

   ヒロシです、みたいな日記になったけど、ギャグではないところが、つらい。
   
   これから、シャワーをあびて、夕飯づくり。
   鶏のレバーを買ってきたのだが、品質が悪く、肉を掃除していると食えるところ少ないんじゃないかというぐらい小くなってしまったモノがあった。
   つらい。

   海外で病気になったとき医者に症状を伝えるためのサインというのがバズられていた(相方に教わった)。
   
   https://twitter.com/yukio8494/status/1116512094315147264

   元ネタは Youtube

   https://twitter.com/yukio8494/status/1116896483394183169

   https://www.youtube.com/watch?v=N_rAmaQXfEA

   便利そう。

   Dired でフォルダの総容量が出るのだけど byte 表示でキツかった。
   以下で解決した。

   #+begin_src elisp
   (setq dired-listing-switches "-la --si --time-style long-iso")
   #+end_src

   以下ではできないとか、できるとか色々書いてあって、つらかった。

   https://stackoverflow.com/questions/30865056/emacs-dired-reverse-date-order

   https://stackoverflow.com/questions/2858097/customizing-dired

   しかし、以下が参考になった。
   
   http://www.wilkesley.org/~ian/xah/emacs/dired_sort.html

   よかった。
   
   xserver から、更新ボタンを押せという案内が来た。
   仕様が変わったらしい。
   つらい。

   - 契約更新手続きの義務化について - 2019/01/30 | 無料レンタルサーバー【エックスフリー】
     - https://www.xfree.ne.jp/news_detail.php?view_id=1872
