* 2019-04-13
** 01:16
   
  あれ時刻が入らない。
  まあ、いいか。
  今日から英語の勉強を再開した。
  といっても、色々調べていただけで、実際の英語の勉強はほとんどしていない。

  I was wondering if I'd left it up there by mistake が早すぎてなかかな言えなかった。
  Has anything been handed in という言い方は口から絶対出てこな言い方だなあと思った。

  left it up の up は VOC の C だという話を相方から貰ってビックリした。
  副詞だと思っていたが、そうかもしれない。
  そういう感覚がないのが悔しいところ。

  speech.sh という google translater を使ってつくったものが残っていた。
  巷に溢れているのは使いものにならなかった。
  google が API を制限したのだろう。
  ここでも公開はしないようにしておこう。
  
  jsay と合わせて瞬間英作文を自分で作れることが分かった。
  
  無音の mp3 を作成するには以下のようにすればいいことが分かった。

  #+begin_src sh
  arecord -d 3 </dev/zero | lame - -b 32 -h silence.mp3
  #+end_src

  上記は 3 秒の無音。
  しかし、その無音の 3 秒間で、ファイルが終了したと見なされる場合が多いことも分かった。
  なので、mp4 への変換

  #+begin_src sh
  ffmpeg -i output.mp3 -shortest -b 1000k -acodec copy output.mp4
  #+end_src

  などとすると、これは前半部分が終った状態で Chrome 再生が止まる場合もあることが分かった。
  VLC でも mp3 で再生すると別の曲として始まる。
  何か 3 秒間のうまいいいものを作らないとという感じ。

  こんなことをやってたら昼飯を食べそこなったので、パン屋で久しぶりにソーセージパンを食べた。

  携帯やイヤホンを見たりした。
  骨伝導を試してみたが、いいような悪いような。フィット感がない。
  イヤホンは耳の穴が蒸れてしまい、外耳炎が悪化するようで、英語の勉強とのトレードオフになることも分かった。
  しかたない。うまくいかないものだ。

  おいしくて安いコーヒー屋をみつけた。
  店員がうるさかった。

  行ってみたかった中華屋に行った。
  ディオニーのワインが飲めるというところで非常によかった。
  安かったし。
  最初会計間違いだったが。

  そのまま有名な担々麺の店で辛くなくてシビれるだけを頼んだ。
  イマイチだった。
  辛い方がいいのかもしれない。
  汁なし。

  相方は辛いのだけで、シビれないように頼んだ。
  イマイチだった。
  合わせて担々麺なんだって分かった。
  

  
